SET SCHEMA SMART_RETAIL1;

CREATE COLUMN TABLE PRODUCT_EMBEDDINGS (
    PRODUCT_ID INT,
    NAME NVARCHAR(100),
    DESCRIPTION NVARCHAR(500),
    VECTOR BLOB
);
CREATE COLUMN TABLE CHAT_LOG (
    ID BIGINT,
    QUESTION NVARCHAR(1000),
    ANSWER NVARCHAR(4000),
    TIMESTAMP TIMESTAMP
);
SELECT * FROM SMART_RETAIL1.PRODUCT_EMBEDDINGS;

