[hana]
HANA_ADDRESS = 6f30991a-1c09-4d97-ad5a-581c884519b0.hana.trial-us10.hanacloud.ondemand.com

HANA_PORT = 443

HANA_USER = APP_USER_STREAMLIT

HANA_PASSWORD = 595162sushiielA@

HANA_SCHEMA = SMART_RETAIL1

HANA_ENCRYPT = true

HANA_SSL_VALIDATE = false
