
address = "5b88e881-d6dd-4f02-8268-0cb145f3e415.hana.trial-us10.hanacloud.ondemand.com"
port = 443
user = "DBADMIN"
password = "595162sushiielA@"
encrypt = true
sslValidateCertificate = false


api_key = Aa59ZsypfvMKRFOMo7E0O32OAVXNAx6r7okISHYt
