[hana]
address = "6f30991a-1c09-4d97-ad5a-581c884519b0.hana.trial-us10.hanacloud.ondemand.com"
port = 443
user = "APP_USER_STREAMLIT"
password = "pR0xy#H4na!A9zQ2w"
encrypt = true
sslValidateCertificate = false
